class TemplateErrorMessages:
    """Error messages for template-related operations"""
    TITLE_REQUIRED = "Template title is required."
    TITLE_MIN_LENGTH = "Template title must be at least 2 characters long."
    TITLE_MAX_LENGTH = "Template title cannot exceed 255 characters."
    DESCRIPTION_MAX_LENGTH = "Template description cannot exceed 5000 characters."
    FILE_REQUIRED = "Template file is required."
    FILE_INVALID_TYPE = "Only .docx files are supported."
    FILE_SIZE_EXCEEDED = "Template file size cannot exceed 10MB."
    TEMPLATE_NOT_FOUND = "Template not found."
    TEMPLATE_INACTIVE = "Template is not active."
    VERSION_INVALID = "Invalid version number."
    PARENT_NOT_FOUND = "Parent template not found."


class DocumentErrorMessages:
    """Error messages for document-related operations"""
    NAME_REQUIRED = "Document name is required."
    NAME_MIN_LENGTH = "Document name must be at least 2 characters long."
    NAME_MAX_LENGTH = "Document name cannot exceed 255 characters."
    TEMPLATE_REQUIRED = "Template is required."
    TEMPLATE_INVALID = "Invalid template selected."
    INPUT_DATA_REQUIRED = "Input data is required."
    INPUT_DATA_INVALID = "Input data format is invalid."
    STATUS_INVALID = "Invalid document status."
    STATUS_UPDATE_NOT_ALLOWED = "Document status cannot be updated in this way."
    DOCUMENT_NOT_FOUND = "Document not found."
    DOCUMENT_FILE_NOT_FOUND = "Document file not found."
    DOCUMENT_NOT_ACCESSIBLE = "You do not have access to this document."
    EXPORT_FORMAT_INVALID = "Invalid export format. Supported formats: docx, pdf, doc."
    NOTES_MAX_LENGTH = "Notes cannot exceed 5000 characters."


class SignatoryErrorMessages:
    """Error messages for signatory-related operations"""
    SIGNATORY_REQUIRED = "Signatory is required."
    SIGNATORY_INVALID = "Invalid signatory selected."
    SIGNATURE_FIELD_REQUIRED = "Signature field name is required."
    SIGNATURE_FIELD_MAX_LENGTH = "Signature field name cannot exceed 255 characters."
    SIGNATURE_ORDER_INVALID = "Invalid signature order."
    STATUS_INVALID = "Invalid signatory status."
    STATUS_UPDATE_NOT_ALLOWED = "Signatory status cannot be updated in this way."
    SIGNATORY_NOT_FOUND = "Signatory not found."
    SIGNATORY_ALREADY_SIGNED = "Signatory has already signed this document."
    SIGNATORY_NOT_PENDING = "You are not a pending signatory for this document."
    PIN_REQUIRED = "PIN is required."
    PIN_INVALID = "Invalid PIN."
    TOTP_REQUIRED = "2FA code is required."
    TOTP_INVALID = "Invalid 2FA code."
    SIGNATURE_FILE_REQUIRED = "Please upload a signature in your profile first."

