# Generated by Django 5.2.8 on 2025-11-29 08:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSignatoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signature_field_name",
                    models.CharField(
                        help_text="Signature field name (e.g., 'requester_1', 'approver_1')",
                        max_length=255,
                    ),
                ),
                (
                    "signature_order",
                    models.IntegerField(
                        default=0, help_text="Order within the field group"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the signature was applied",
                        null=True,
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        help_text="Stored signature image after signing",
                        null=True,
                        upload_to="signatures/applied/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("signed", "Signed")],
                        default="pending",
                        help_text="Signature status",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Signatory",
                "verbose_name_plural": "Document Signatories",
                "ordering": ["signature_field_name", "signature_order"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocumentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name/Title for this generated document",
                        max_length=255,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict,
                        help_text="Input data used to generate the document (stored as JSON)",
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        help_text="The generated document file",
                        upload_to="generated_documents/",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("docx", "DOCX"), ("pdf", "PDF"), ("doc", "DOC")],
                        default="docx",
                        help_text="Format of the generated document",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("signed", "Signed"),
                        ],
                        default="generated",
                        help_text="Status of the document",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the document was approved/signed",
                        null=True,
                    ),
                ),
                (
                    "signatories_count",
                    models.IntegerField(
                        default=0, help_text="Total number of signatories required"
                    ),
                ),
                (
                    "signed_count",
                    models.IntegerField(
                        default=0, help_text="Number of signatories who have signed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this document",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Document",
                "verbose_name_plural": "Generated Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("file", models.FileField(upload_to="templates/")),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
    ]
