# Generated by Django 5.2.8 on 2025-11-29 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document_control", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsignatorymodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentsignatorymodel",
            name="signatory",
            field=models.ForeignKey(
                help_text="User assigned to sign",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatory_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentsignatorymodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocumentmodel",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved/signed this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocumentmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocumentmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocumentmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who generated this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentsignatorymodel",
            name="document",
            field=models.ForeignKey(
                help_text="Document requiring signature",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatories",
                to="document_control.generateddocumentmodel",
            ),
        ),
        migrations.AddField(
            model_name="templatemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templatemodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="document_control.templatemodel",
            ),
        ),
        migrations.AddField(
            model_name="templatemodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocumentmodel",
            name="template",
            field=models.ForeignKey(
                help_text="Template used to generate this document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_documents",
                to="document_control.templatemodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentsignatorymodel",
            unique_together={
                ("document", "signatory", "signature_field_name", "signature_order")
            },
        ),
        migrations.AlterUniqueTogether(
            name="templatemodel",
            unique_together={("parent", "version")},
        ),
    ]
