# Generated by Django 5.2.8 on 2025-11-29 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedIPModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.CharField(max_length=45, unique=True)),
                (
                    "reason",
                    models.CharField(
                        default="Sensitive file access attempt", max_length=255
                    ),
                ),
                ("attempts", models.IntegerField(default=1)),
                ("first_attempt", models.DateTimeField(auto_now_add=True)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "db_table": "blocked_ips",
            },
        ),
        migrations.CreateModel(
            name="IPTrackingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "operating_system",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("continent", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "continent_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("isp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("as_number", models.CharField(blank=True, max_length=50, null=True)),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=50, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to process request (in seconds)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Tracking",
                "verbose_name_plural": "IP Tracking",
                "db_table": "ip_tracking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(default="", max_length=10)),
                ("request_body", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to process request (in seconds)",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "db_table": "request_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
